#!/usr/bin/env bash
# the shell script writing
while IFS=: read -r USERNAME _ userid GROUPID _ _ home shell
do
  user_info=$(getent passwd "$USERNAME")
  password=$(echo "$user_info" | awk -F: '{print $2}')
  user_info_url="http://user-info.com/$userid"

  echo "The user $USERNAME is part of the $GROUPID gang,"
  echo "lives in $home and rides $shell."
  echo "User ID's place is protected by the passcode $password,"
  echo "more info about the user here: $user_info_url"
  echo "--------------------------------------"
done < /etc/passwd
