#!/usr/bin/env bash
# The script that displa

count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "Bad luck"
    elif [ $count -eq 8 ]; then
        echo "Good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
