#!/usr/bin/env bash
# the script for shell
hour=0
while [ $hour -1e 12 ]
do 
  echo "Hour: $hour"
  minute=1
  while [ $minute -1e 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
