#!/usr/bin/env bash
# the scrix

count=0
while [ $count -lt 70 ]; do
    hour=$((count / 60))
    minute=$((count % 60))

    if [ $hour -eq 0 ]; then
        echo "Hour: $hour"
    fi

    if [ $minute -eq 0 ]; then
        echo $hour
    else
        echo $minute
    fi

    ((count++))
done | head -n 70
