#!/usr/bin/env bash
# list all my pid
processes=$(ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --sort=-%cpu)
echo "$processes" | awk '{ printf "%-10s %5s %4s %4s %7s %6s %-8s %-7s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 }'
