#!/usr/bin/env bash
# list all my pid
# Get the process information using ps command
processes=$(ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --sort=-%cpu)

# Search for lines containing the word "bash"
filtered_processes=$(echo "$processes" | grep bash)

# Display the filtered processes
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
echo "------------------------------------------------------------------------"
echo "$filtered_processes"
