#!/usr/bin/env bash
# bash script
shopt -s nullglob
for pid_dir in /proc/[0-9]*/; do
    pid=$(basename "$pid_dir")
    if [[ -f "$pid_dir/status" ]]; then
        process_name=$(awk '/Name/ {print $2}' "$pid_dir/status")
        if [[ $process_name == *bash* ]]; then
            echo "PID: $pid, Process Name: $process_name"
        fi
    fi
done
